#!/usr/bin/env python3
"""Regenerate assets/pages.js — the page order used for prev/next links and the breadcrumb.

    python3 tools/setpages.py            # write assets/pages.js from the folder contents
    python3 tools/setpages.py --check    # exit 1 if assets/pages.js is out of date (used by tools/check_all.py)

The rule is deliberately mechanical so that several people (or several agents) can add a
chapter without editing a shared list:

  * order      = numeric filename prefix (01-, 02-, …); index.html always first
  * label      = the page's <title> up to the first " — "
  * brand/ls   = the folder name and index.html's title, so notes.js holds no topic-specific string
                 and a new topic folder needs no editing of the shared script
  * a page that is not listed is a page that does not exist as far as navigation is concerned,
    so `python3 tools/setpages.py` is part of "add a chapter", not an afterthought.
"""
import re, os, sys, glob, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'pages.js')
HEADER = ("/* GENERATED by tools/setpages.py \u2014 do not edit by hand.\n"
          "   order: numeric filename prefix, index.html first;  label: <title> up to the first em-dash. */\n")


def pages():
    files = sorted(os.path.basename(p) for p in glob.glob(os.path.join(ROOT, '*.html')))
    def key(f):
        m = re.match(r'(\d+)-', f)
        return (0, 0) if f == 'index.html' else (1, int(m.group(1)) if m else 9999)
    out = []
    for f in sorted(files, key=key):
        src = open(os.path.join(ROOT, f), encoding='utf-8').read()
        m = re.search(r'<title>(.*?)</title>', src, re.S)
        label = (m.group(1) if m else os.path.splitext(f)[0])
        label = re.split(r'\s\u2014\s|\s-\s', label)[0].strip()
        label = html.unescape(re.sub(r'<[^>]*>', '', label)).strip()
        if f == 'index.html':
            label = 'Home \u00b7 overview'          # the front page needs no breadcrumb
        out.append((f, label))
    return out


def site():
    """(brand, ls-prefix) for the whole folder: derived, never hand-written."""
    name = os.path.basename(ROOT)
    idx = os.path.join(ROOT, 'index.html')
    brand = name.replace('-', ' ').title()
    if os.path.exists(idx):
        m = re.search(r'<title>(.*?)</title>', open(idx, encoding='utf-8').read(), re.S)
        if m:
            brand = html.unescape(re.sub(r'<[^>]*>', '', m.group(1))).split('\u2014')[0].strip() or brand
    return brand, 'notes:%s:' % name


def render():
    import json
    body = ',\n'.join('    ' + json.dumps([f, l], ensure_ascii=False) for f, l in pages())
    brand, ls = site()
    return (HEADER
            + 'window.NOTES_SITE = {\n'
            + '  brand: %s,\n  ls: %s,\n  pages: [\n%s\n  ]\n};\n'
            + 'window.NOTES_PAGES = window.NOTES_SITE.pages;\n') % (json.dumps(brand, ensure_ascii=False),
                                                                     json.dumps(ls), body)


if __name__ == '__main__':
    want = render()
    have = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if '--check' in sys.argv:
        if want == have:
            print('pages.js is up to date (%d pages)' % len(pages()))
        else:
            print('pages.js is STALE \u2014 run: python3 tools/setpages.py')
            sys.exit(1)
    else:
        open(OUT, 'w', encoding='utf-8').write(want)
        print('wrote assets/pages.js: ' + ', '.join(l for _, l in pages()))
