#!/usr/bin/env python3
"""Editable SVG companions for Heat (D17) and Capacitors (D18).

Course slots 16–18 also include Electrostatics, whose existing D13 scenes are
validated, never regenerated by this builder. Standard library only. Original
SVGs and Markdown content are retained; no HTML exporter is invoked.
"""
from __future__ import annotations
import json
import math
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from tools.build_excalidraw_batch import Scene, scene_file, INK, MUTED, GRID, BLUE, WHITE, RED, GREEN, ORANGE
from tools.build_excalidraw_waves_thermal import (
    ROOT, NS, NUMBER, IDENTITY, Matrix, matmul, point, css_rules, path_polylines, add_path,
    draw_style as base_style, colour as base_colour,
)
TOPICS={'heat':('Heat.md',17,25),'capacitors':('Capacitors.md',18,32)}


def transform_matrix(raw: str) -> Matrix:
    m=IDENTITY
    for kind,args in re.findall(r'([A-Za-z]+)\s*\(([^)]+)\)',raw):
        v=[float(x) for x in re.findall(NUMBER,args)]
        if kind=='translate':op=(1,0,0,1,v[0],v[1] if len(v)>1 else 0)
        elif kind=='scale':op=(v[0],0,0,v[1] if len(v)>1 else v[0],0,0)
        elif kind=='rotate':
            a=math.radians(v[0]);co,si=math.cos(a),math.sin(a)
            op=(co,si,-si,co,0,0)
            if len(v)==3:
                op=matmul(matmul((1,0,0,1,v[1],v[2]),op),(1,0,0,1,-v[1],-v[2]))
        else:raise ValueError(f'unsupported transform: {kind}')
        m=matmul(m,op)
    return m


def draw_style(el,parent,variables,rules):
    result=base_style(el,parent,variables,rules)
    for k,v in result.items():
        result[k]=re.sub(r'var\((--[\w-]+),\s*([^)]+)\)',lambda m:variables.get(m[1],m[2]),v)
    if result.get('font-size')=='Nonepx':result['font-size']='13px'
    return result


def colour(value):
    # SVG colour-mix fills use two resolved hex colours and one percentage.
    match=re.fullmatch(r'color-mix\(in srgb,\s*(#[0-9a-fA-F]{6}) (\d+)%\s*,\s*(#[0-9a-fA-F]{6})\)',value)
    if match:
        a,p,b=match.groups();f=float(p)/100
        return '#'+''.join(f'{round(int(a[i:i+2],16)*f+int(b[i:i+2],16)*(1-f)):02x}' for i in (1,3,5))
    return base_colour(value)


def wording(slug,stem,value):
    fixes={
        ('capacitors','fig-013'):{'the 12 edges become 3 groups of 3':'the 12 edges form groups of 3, 6 and 3'},
        ('capacitors','fig-018'):{'E is stronger on the high-κ side of any dipole ⇒ net pull to the right':'The dielectric is pulled toward increasing overlap; F = ½V² dC/dx.'},
        ('heat','fig-007'):{'ice at 0 °C, open to −20 °C air':'ice: colder at top, 0 °C at water interface'},
        ('heat','fig-008'):{'plateau length × heater power = mL; the graph is a calorimeter':'On this Q axis: plateau width = mL (not width × power).'},
        ('heat','fig-009'):{'melts 0.080 kg ice':'melts 0.80 kg ice', '+ 1.0 kg meltwater':'+ 0.90 kg liquid water',
                            'supply 267.5 kJ < the 752 kJ that melting+boiling everything would need ⇒ the final state is pinned at 0 °C, two phases':'267.5 kJ < 334 kJ needed to melt all the ice: final T = 0 °C, two phases'},
        ('heat','fig-017'):{'surface sets the pace':'internal gradients matter'},
        ('heat','fig-010'):{"water's line bends and steepens near the critical point, where L → 0: the straight-line law has a shelf life":
                           'Near the critical point, the constant-L ideal-vapour approximation fails.'},
        ('heat','fig-013'):{'for a 5 mm fuel pellet at 5×10⁸ W/m³ with k = 2.8: 446 K hotter in the middle':
                           'plane slab: a = half-thickness; constant k and uniform volumetric generation'},
        ('heat','fig-025'):{'r_c = k/h — adding R_conv faster than R_cond grows':
                           'r_c = k/h: R_conv falls while R_cond grows; total resistance is minimum'},
    }
    for old,new in fixes.get((slug,stem),{}).items():value=value.replace(old,new)
    return value


def converted_scene(slug: str, fig: Path, key: str) -> Scene:
    root=ET.parse(fig).getroot(); vb=list(map(float,root.get('viewBox','0 0 800 500').split()))
    if len(vb)!=4:raise ValueError(f'{fig}: missing viewBox')
    # Uniform scale keeps each source figure's geometry intact.
    scale=min(2.0,1360/vb[2]);offset=(32-vb[0]*scale,126-vb[1]*scale)
    global_matrix:Matrix=(scale,0,0,scale,*offset)
    vars,rules=css_rules(root)
    vars.update({'--bg':'#ffffff','--surface':'#f4f6f9','--surface-2':'#edf4fb',
                 '--accent-soft':'#e9f2fb'})
    # The extracted HTML maps omit their parent stylesheet.
    rules.update({'.t1':{'font-size':'13px','fill':INK},
                  '.t2':{'font-size':'11px','fill':MUTED},
                  '.num':{'font-size':'12px','fill':BLUE}})
    is_map=slug=='heat' and fig.stem=='fig-001'
    if is_map:
        for el in root.iter():
            if el.tag==NS+'text' and el.get('style','').find('fill:#fff')>=0:
                el.set('style','fill:'+INK)
    s=Scene(key);s.title(f'{slug.replace("-"," ").title()} · {fig.stem}',
                         'Editable companion to the local SVG; source figure is retained in the chapter.')
    def walk(el: ET.Element, mat: Matrix, inherited: dict[str,str]):
        tag=el.tag.removeprefix(NS)
        if tag in ('style','defs','marker','pattern','title','desc'):return
        if tag not in {'g','a','text','rect','circle','ellipse','line','path','polygon','polyline'}:
            raise ValueError(f'{fig}: unsupported SVG element {tag}')
        before=len(s.elements)
        style=draw_style(el,inherited,vars,rules)
        own=transform_matrix(el.get('transform',''))
        # Compose an explicit transform origin when present.
        origin=el.get('transform-origin')
        if origin and 'scale' in el.get('transform',''):
            ox,oy=(float(v) for v in origin.split())
            own=matmul(matmul((1,0,0,1,ox,oy),own),(1,0,0,1,-ox,-oy))
        mat=matmul(mat,own)
        stroke=colour(style.get('stroke','none'));fill=colour(style.get('fill','black'))
        if tag=='rect' and fill==INK:
            fill='#edf4fb';stroke=BLUE
        if is_map and tag=='path':stroke=GRID;fill='transparent'
        if is_map and tag=='text':
            style['fill']=INK
        width=float(style.get('stroke-width','1.6'))*math.hypot(mat[0],mat[1])
        dashed='stroke-dasharray' in style
        def P(x,y):return point(mat,float(x),float(y))
        if tag=='text':
            x,y=P(el.get('x','0'),el.get('y','0'))
            value=''.join(el.itertext()).strip()
            value=wording(slug,fig.stem,value)
            if (slug,fig.stem)==('heat','fig-003'):value=value.replace('∐v²∑','⟨v²⟩')
            replacements={
                'the whole course · click a branch':'the whole course',
                'every chapter opens in place':'eight chapter branches',
                'every Joule-expansion demo':'every throttling process',
                'At M=1, α=90° (plane wave)':'as M → 1⁺, α → 90°',
            }
            for old,new in replacements.items():value=value.replace(old,new)
            if value:
                size=int(max(12,min(26,float(style.get('font-size','13').removesuffix('px'))*math.hypot(mat[0],mat[1]))))
                # SVG y is the baseline, Excalidraw y is the top.
                text_w=max(80,len(value)*size*.58)
                if style.get('text-anchor')=='middle':x-=text_w/2
                if style.get('text-anchor')=='end':x-=text_w
                # Rotate around the SVG baseline anchor, not the top-left of the box.
                anchor_x,anchor_y=P(el.get('x','0'),el.get('y','0'))
                angle=math.atan2(mat[1],mat[0])
                dx=x+text_w/2-anchor_x;dy=(size*1.35+8)/2-size*.95
                cx=anchor_x+dx*math.cos(angle)-dy*math.sin(angle)
                cy=anchor_y+dx*math.sin(angle)+dy*math.cos(angle)
                s.text(cx-text_w/2,cy-(size*1.35+8)/2,value,size,colour(style.get('fill','black')),text_w)
                s.elements[-1]['angle']=angle
        elif tag=='rect':
            def length(raw,view):return view*float(raw[:-1])/100 if raw.endswith('%') else float(raw)
            x=float(el.get('x','0'));y=float(el.get('y','0'))
            w=length(el.get('width','0'),vb[2]);h=length(el.get('height','0'),vb[3])
            if w>0 and h>0:
                cx,cy=P(x+w/2,y+h/2);ww=w*math.hypot(mat[0],mat[1]);hh=h*math.hypot(mat[2],mat[3])
                s.rect(cx-ww/2,cy-hh/2,ww,hh,stroke,fill,max(1,width),bool(el.get('rx')),math.atan2(mat[1],mat[0]))
                if dashed:s.elements[-1]['strokeStyle']='dashed'
        elif tag in ('circle','ellipse'):
            cx,cy=P(el.get('cx','0'),el.get('cy','0'))
            rx=float(el.get('r',el.get('rx','0')))*math.hypot(mat[0],mat[1])
            ry=float(el.get('r',el.get('ry','0')))*math.hypot(mat[2],mat[3])
            if rx>0 and ry>0:
                s.ellipse(cx-rx,cy-ry,2*rx,2*ry,stroke,fill,max(1,width))
                s.elements[-1]['angle']=math.atan2(mat[1],mat[0])
        elif tag in ('polygon','polyline'):
            nums=[float(v) for v in re.findall(NUMBER,el.get('points',''))]
            pts=[P(*nums[i:i+2]) for i in range(0,len(nums),2)]
            add_path(s,pts+[pts[0]] if tag=='polygon' else pts,stroke,fill,width,dashed,'marker-end' in style,'marker-start' in style)
        elif tag=='line':
            p=P(el.get('x1','0'),el.get('y1','0'));q=P(el.get('x2','0'),el.get('y2','0'))
            if p!=q:add_path(s,[p,q],stroke if stroke!='transparent' else INK,'transparent',width,dashed,'marker-end' in style,'marker-start' in style)
        elif tag=='path':
            for curve in path_polylines(el.get('d','')):
                add_path(s,[P(*v) for v in curve],stroke,
                         fill if curve[0]==curve[-1] else 'transparent',width,dashed,'marker-end' in style,'marker-start' in style)
        else:
            for child in el:walk(child,mat,style)
        if tag not in ('g','a'):
            for element in s.elements[before:]:
                element['opacity']=round(100*float(style.get('opacity','1')))

    for child in root:walk(child,global_matrix,{'fill':'black','stroke':'none'})
    # Reflow long prose below the diagram rather than across adjacent panels.
    # Retain exact wording; free text is independently editable.
    if not is_map:
        import textwrap
        annotations=[e for e in s.elements[2:] if e['type']=='text' and (len(e['text'])>42 or e['text'].startswith('F = ε₀'))]
        bottom=max(e['y']+e['height'] for e in s.elements)+24
        for e in annotations:
            value='\n'.join(textwrap.wrap(e['text'],width=98,break_long_words=False))
            e.update(x=60,y=bottom,width=1250,fontSize=20,text=value,originalText=value,
                     height=27*len(value.splitlines())+8,angle=0)
            bottom+=e['height']+12
    if len(s.elements)<5:raise ValueError(f'{fig}: suspiciously empty conversion')
    return s


def plot(s, fn, xmin, xmax, x=150, y=510, w=1000, h=330, color=BLUE, steps=240):
    pts=[(x+w*i/steps,y-h*fn(xmin+(xmax-xmin)*i/steps)) for i in range(steps+1)]
    add_path(s,pts,color,'transparent',2.6)
    return pts


def axes(s, xlabel, ylabel):
    s.arrow(150,510,1190,510,INK);s.arrow(150,510,150,140,INK)
    s.text(1200,495,xlabel,20,INK,170);s.text(45,110,ylabel,20,INK,300)


def corrected_scene(slug,fig,key):
    n=int(fig.stem[4:]);s=Scene(key)
    extra=additional_scene(slug,n,key)
    if extra:return extra
    if slug=='heat' and n==11:
        s.title('Series conduction: lowest conductivity means steepest temperature gradient',
                'Steady one-dimensional heat flow; equal area, perfect contacts and constant k.')
        axes(s,'x','T')
        ks=[385,.8,.026];lengths=[.02,.02,.02];R=[l/k for l,k in zip(lengths,ks)]
        total=sum(R);drop=0
        for i,(k,label,c) in enumerate(zip(ks,['copper','glass','air'],[BLUE,RED,GREEN])):
            a=150+i*330;b=a+330;y1=180+drop/total*300;drop+=R[i];y2=180+drop/total*300
            s.line(a,y1,b,y2,c,3);s.line(a,510,a,160,GRID,1.2,'dashed')
            s.text(a+25,540,f'{label}: k = {k}',20,c,320)
        s.text(150,600,'|dT/dx| = heat flux / k. With equal thickness, air takes almost all the temperature drop.',21,INK,1200)
        s.text(150,645,'R_th = Σ Lᵢ/(kᵢ A); heat rate = (T_hot − T_cold)/R_th. k in W m⁻¹ K⁻¹.',20,INK,1200)
    elif slug=='heat' and n==12:
        s.title('Radial conduction: temperature is linear in ln r',
                'Long cylindrical shell, constant conductivity, steady flow and no internal heat generation.')
        axes(s,'ln(r/r₁)','(T − T₂)/(T₁ − T₂)')
        plot(s,lambda z:1-z,0,1)
        s.text(150,540,'0',20);s.text(1040,540,'ln(r₂/r₁)',20)
        s.text(150,595,'T(r) = T₁ − (T₁ − T₂) ln(r/r₁) / ln(r₂/r₁)',23,BLUE,1200)
        s.text(150,640,'R_th = ln(r₂/r₁)/(2πkL); |dT/dr| ∝ 1/r, because the flow area is 2πrL.',21,INK,1200)
    elif (slug,n) in {('heat',16),('capacitors',24)}:
        cap=slug=='capacitors'
        s.title('RC step response: rise, decay and the correct time markers' if cap else 'Newton cooling: exact exponential and time markers',
                'Constant parameters; an ideal step through finite resistance.' if cap else 'Lumped body, constant ambient temperature and constant h; Bi ≪ 0.1.')
        axes(s,'t/τ','normalised voltage' if cap else 'ΔT/ΔT_initial')
        plot(s,lambda t:math.exp(-t),0,5,color=RED)
        if cap:plot(s,lambda t:1-math.exp(-t),0,5)
        for t,label in [(math.log(2),'ln 2'),(1,'1'),(math.log(10),'ln 10')]:
            x=150+200*t;y=510-330*math.exp(-t)
            s.line(x,510,x,180,GRID,1.2,'dashed');s.dot(x,y,4,RED);s.text(x-18,540,label,18,INK,130)
        if cap:
            s.line(150,510,350,180,ORANGE,2,'dashed')
            s.text(670,180,'V_C/V∞ = 1 − e^(−t/τ)',22,BLUE,650)
            s.text(670,230,'V_R/V∞ = e^(−t/τ)',22,RED,650)
            s.text(150,600,'τ = R_th C; I = (V∞ − V_C)/R_th; Q = CV_C; U_C = ½CV_C².',22,INK,1220)
            s.text(150,640,'The initial charging tangent reaches V∞ at τ; after 5τ, 0.67% remains.',21,INK,1220)
            s.text(150,680,'General step: V_C(t) = V∞ + [V_C(0⁺) − V∞]e^(−t/τ).',21,INK,1220)
        else:
            s.text(650,180,'ΔT = ΔT_initial e^(−t/τ)',23,RED,650)
            s.text(150,600,'τ = mc/(hA). At τ: 36.8% remains; at ln(10)τ ≈ 2.303τ: 10% remains.',21,INK,1200)
            s.text(150,645,'Half-life = ln(2)τ ≈ 0.693τ. The baseline means T = T_ambient, not T = 0 K.',21,INK,1200)
    elif slug=='heat' and n==18:
        s.title('Blackbody spectra: hotter peaks at a shorter wavelength',
                'Each curve is normalised to its own peak to show peak position; heights are NOT absolute radiance.')
        axes(s,'λ (μm, log)','Bλ / Bλ,max')
        for T,c in [(5800,RED),(1500,ORANGE),(300,BLUE)]:
            peak=2897.77/T
            def fn(loglam):
                lam=10**loglam;u=14387.77/(lam*T);up=14387.77/(peak*T)
                return (peak/lam)**5*math.expm1(up)/math.expm1(u) if u<700 else 0
            plot(s,fn,-1,2,color=c,steps=500)
            x=150+1000*(math.log10(peak)+1)/3
            s.line(x,510,x,180,c,1,'dashed');s.text(x-25,535,f'{peak:.2f}',18,c,120)
        for i,(txt,c) in enumerate([('5800 K: 0.50 μm',RED),('1500 K: 1.93 μm',ORANGE),('300 K: 9.66 μm',BLUE)]):s.text(180+i*365,600,txt,22,c,370)
        s.text(150,650,'λ_max T = 2898 μm K. Absolute peak radiance grows as T⁵; integrated exitance = σT⁴.',21,INK,1220)
    elif slug=='capacitors' and n==1:
        s.title('Parallel plates connected to one battery',
                'Ideal large plates: ignore fringing in the central region. The battery fixes V, not Q.')
        s.rect(160,190,700,12,BLUE,'#e9f2fb');s.rect(160,420,700,12,RED,'#faeceb')
        for x in range(220,830,120):
            s.text(x,150,'+',24,BLUE,40);s.text(x,450,'−',24,RED,40);s.arrow(x,225,x,390,BLUE,2)
        s.line(860,196,1080,196);s.line(1080,196,1080,295)
        s.line(860,426,1080,426);s.line(1080,426,1080,325)
        s.line(1035,295,1125,295,INK,3);s.line(1055,325,1105,325,INK,3)
        s.text(1140,285,'+  V₀',22,INK,160);s.text(1140,325,'−',22)
        s.text(370,535,'E = V₀/d = Q/(ε₀A); C = ε₀A/d',24,BLUE,900)
        s.text(160,600,'Top plate +Q, bottom plate −Q. If the battery is disconnected, total plate charge is fixed.',21,INK,1200)
    elif slug=='capacitors' and n==11:
        s.title('Pull-in: tangency of two force curves',
                'g = remaining gap, g₀ = unstretched gap. Fixed voltage; ideal parallel plates and linear spring.')
        axes(s,'g/g₀','F/(kg₀)')
        plot(s,lambda z:1-z,.4,1,color=GREEN)
        plot(s,lambda z:4/(27*z*z),.4,1,color=RED)
        x=150+1000*((2/3-.4)/.6);y=510-330/3
        s.dot(x,y,6,INK);s.line(x,510,x,y,MUTED,1.4,'dashed');s.text(x-50,540,'2/3',22)
        s.text(780,175,'F_s = k(g₀ − g)',22,GREEN,500);s.text(780,220,'F_e = ε₀AV²/(2g²)',22,RED,500)
        s.text(150,600,'At V_pi² = 8kg₀³/(27ε₀A): g = 2g₀/3, deflection = g₀/3.',22,INK,1200)
        s.text(150,645,'Below pull-in: the larger-gap equilibrium is stable, the smaller-gap one unstable.',21,INK,1200)
        s.text(150,685,'Above pull-in there is no equilibrium. At the threshold the slopes also match.',21,INK,1200)
    elif slug=='capacitors' and n==14:
        s.title('Infinite capacitor ladder: preserve every junction',
                'One series C, followed by a shunt C in parallel with the remaining infinite ladder.')
        def horizontal(a,b,y):
            mid=(a+b)/2;s.line(a,y,mid-10,y);s.line(mid+10,y,b,y)
            s.line(mid-10,y-30,mid-10,y+30,BLUE,3);s.line(mid+10,y-30,mid+10,y+30,BLUE,3)
            s.text(mid-8,y-65,'C',22,BLUE)
        s.line(100,470,1180,470)
        last=100
        for x in [390,690,990]:
            horizontal(last,x,230);s.dot(x,230,5)
            s.line(x,230,x,335);s.line(x,365,x,470)
            s.line(x-30,335,x+30,335,BLUE,3);s.line(x-30,365,x+30,365,BLUE,3)
            s.text(x+45,330,'C',22,BLUE);last=x
        s.line(last,230,1180,230);s.text(1210,220,'…',25);s.text(1210,455,'…',25)
        s.dot(100,230,5);s.dot(100,470,5)
        s.text(150,550,'Let X be the input capacitance: X = C(C + X)/(2C + X).',23,INK,1220)
        s.text(150,600,'X² + CX − C² = 0 ⇒ X = (√5 − 1)C/2 ≈ 0.618C.',23,BLUE,1220)
    elif slug=='capacitors' and n==31:
        s.title('Two instabilities: MEMS pull-in and the Rayleigh limit',
                'Different stability problems: a plate deflection versus a volume-preserving droplet shape distortion.')
        s.text(120,145,'MEMS · fixed voltage',24,BLUE,650)
        s.text(120,195,'u = deflection/g₀; λ = ε₀AV²/(2kg₀³)',20,INK,1100)
        s.text(120,235,'Π/(kg₀²) = ½u² − λ/(1 − u)',22,BLUE,1100)
        s.text(120,280,'Equilibria: u(1 − u)² = λ. Stable if u < 1/3.',21,INK,1150)
        s.text(120,325,'At λ = 4/27: minimum and maximum merge at u = 1/3.',21,INK,1150)
        s.text(120,400,'DROPLET · fixed volume, conducting liquid',24,GREEN,1150)
        s.text(120,450,'Q_R² = 64π²ε₀γR³; γ is surface tension.',23,GREEN,1150)
        s.text(120,495,'The quadrupole shape mode loses stability at Q_R.',21,INK,1150)
        s.text(120,535,'Do not derive this by minimising U(R): fixed volume does not allow arbitrary changes in R.',21,INK,1200)
        s.text(120,600,'Taylor cone: ideal electrostatic half-angle ≈ 49.3°; E ∝ distance^(−1/2) near the apex.',21,INK,1200)
        s.text(120,640,'The ideal apex field is singular. Real emission requires a finite microscopic cutoff.',21,INK,1200)
    else:return None
    return s


def additional_scene(slug,n,key):
    s=Scene(key)
    if slug=='heat' and n==5:
        s.title('Clamped rod: heating produces compression',
                'Uniform rod, both ends rigidly fixed; small strain, elastic response, no buckling.')
        s.rect(200,260,950,70,RED,'#faeceb')
        s.rect(170,190,30,210,INK,'#e4e4e4');s.rect(1150,190,30,210,INK,'#e4e4e4')
        s.arrow(90,295,340,295,RED,4);s.arrow(1270,295,1010,295,RED,4)
        s.text(390,200,'rod heated by ΔT > 0; total length cannot change',22,INK,800)
        s.text(200,480,'Thermal strain + mechanical strain = 0: αΔT + σ/Y = 0.',23,INK,1200)
        s.text(200,535,'Tensile-positive convention: σ = −YαΔT; compressive force magnitude = AYαΔT.',21,RED,1200)
    elif slug=='heat' and n==22:
        s.title('Thermal wave: depth attenuates and delays the surface oscillation',
                'Semi-infinite homogeneous medium with a sinusoidal surface temperature; α is thermal diffusivity.')
        s.arrow(150,360,1190,360,INK);s.arrow(150,520,150,160,INK)
        for fn,c in [(lambda z:math.exp(-z)*math.cos(z),BLUE),(lambda z:math.exp(-z),MUTED),(lambda z:-math.exp(-z),MUTED)]:
            plot(s,fn,0,6,y=360,h=170,color=c)
        s.text(1200,345,'x/δ',22);s.text(150,115,'(T − mean T)/surface amplitude at t = 0',22,INK,1000)
        s.text(150,570,'T − mean T = A e^(−x/δ) cos(ωt − x/δ), δ = √(2α/ω).',23,BLUE,1200)
        s.text(150,620,'At x = πδ the phase is reversed, but only e^(−π) ≈ 4.3% of the surface amplitude remains.',21,INK,1200)
    elif slug=='capacitors' and n==28:
        s.title('Weighting field: induced charge depends on position',
                'Point charge +q between infinite grounded plates, separation d. Let x be distance from plate 1.')
        s.line(210,200,210,480,INK,4);s.line(720,200,720,480,INK,4)
        s.dot(400,340,9,RED);s.text(420,330,'+q',24,RED)
        s.arrow(210,530,400,530,MUTED,2,start='arrow');s.text(285,545,'x',22)
        s.arrow(210,170,720,170,MUTED,2,start='arrow');s.text(450,125,'d',22)
        s.text(160,590,'Q₁ = −q(1 − x/d); Q₂ = −qx/d; Q₁ + Q₂ = −q.',23,BLUE,1250)
        s.text(160,640,'For motion toward plate 2: dQ₁/dt = qv/d. Pulse area = q Δx/d for this one carrier.',21,INK,1250)
        s.text(160,680,'A full-gap traversal gives magnitude q; a partial traversal does not.',21,INK,1250)
        s.text(820,245,'Weighting potential',23,BLUE,550)
        s.text(820,290,'φ₁(x) = 1 − x/d',23,INK,500)
        s.text(820,345,'Set plate 1 to 1 V,',21,INK,500)
        s.text(820,380,'plate 2 to 0 V.',21,INK,500)
        s.text(820,425,'|E_weight| = 1/d',23,BLUE,500)
    elif slug=='heat' and n==6:
        s.title('Bimetal strip: the higher-expansion metal lies on the outside',
                'Bonded brass and steel, heated uniformly; brass wants the larger length change.')
        for r,c in [(210,BLUE),(180,RED)]:
            pts=[(680+r*math.cos(t),480-r*math.sin(t)) for t in [math.pi*i/120 for i in range(121)]]
            add_path(s,pts,c,'transparent',10)
        s.text(200,165,'Brass: α ≈ 19 × 10⁻⁶ K⁻¹ · larger radius, outer arc',23,BLUE,1120)
        s.text(200,210,'Steel: α ≈ 12 × 10⁻⁶ K⁻¹ · smaller radius, inner arc',23,RED,1120)
        s.text(200,555,'The strip bends toward steel. Both layers subtend the same angle; outer arc length is larger.',21,INK,1150)
        s.text(200,600,'Curvature depends on thicknesses, elastic moduli and (α_brass − α_steel)ΔT.',21,INK,1150)
    elif slug=='capacitors' and n==9:
        s.title('Coaxial capacitor: field is zero in metal, proportional to 1/r in the gap',
                'Long coaxial conductors, radii a and b; line charge +λ on the inner conductor, −λ on the outer.')
        axes(s,'r/a','E / [λ/(2πε₀a)]')
        s.line(150,510,350,510,INK,3);s.line(350,510,350,180,BLUE,2)
        plot(s,lambda z:1/z,1,3,x=350,w=600)
        s.line(950,400,950,510,BLUE,2);s.line(950,510,1150,510,INK,3)
        s.text(340,545,'a',22);s.text(940,545,'b = 3a',22)
        s.text(150,600,'V = λ ln(b/a)/(2πε₀); C = 2πε₀L / ln(b/a).',23,BLUE,1180)
        s.text(150,650,'The discontinuities at a and b are surface-charge jumps—not smooth ramps.',21,INK,1180)
    elif slug=='capacitors' and n==21:
        s.title('Debye relaxation: dispersion, loss and the semicircle',
                'Convention κ* = κ′ − iκ″ with κ″ ≥ 0; the right panel plots positive loss upward.')
        for x in [100,760]:
            s.arrow(x,480,x+490,480,INK);s.arrow(x,480,x,160,INK)
        for fn,c in [(lambda u:1/(1+10**(2*u)),BLUE),(lambda u:10**u/(1+10**(2*u)),RED)]:
            plot(s,fn,-3,3,x=100,w=480,y=480,h=270,color=c)
        s.text(100,125,'(κ′−κ∞)/Δκ, κ″/Δκ',20,INK,650)
        s.text(320,515,'log₁₀(ωτ)',20)
        pts=[(760+480*(1+math.cos(t))/2,480-480*math.sin(t)/2) for t in [math.pi*i/180 for i in range(181)]]
        add_path(s,pts,BLUE,'transparent',3)
        s.text(785,125,'κ″/Δκ',20);s.text(1020,515,'(κ′−κ∞)/Δκ',20,INK,400)
        s.text(800,545,'0',20);s.text(1225,545,'1',20)
        s.text(150,600,'Δκ = κ_s − κ∞. Loss peaks at ωτ = 1 with κ″ = Δκ/2.',22,RED,1180)
        s.text(150,645,'[(κ′−κ∞)/Δκ − ½]² + (κ″/Δκ)² = ¼.',22,BLUE,1180)
    elif slug=='capacitors' and n==22:
        s.title('Ferroelectric hysteresis: remanence and coercive field',
                'Schematic saturating branches. P_r is the intercept at E = 0; P_s is the saturation value.')
        s.arrow(160,360,1180,360,INK);s.arrow(650,570,650,130,INK)
        for shift,c in [(-.35,BLUE),(.35,RED)]:
            pts=[(650+450*z,360-180*math.tanh(3*(z-shift))) for z in [-1+2*i/240 for i in range(241)]]
            add_path(s,pts,c,'transparent',3)
        s.text(1180,350,'E',23);s.text(665,120,'P',23)
        for z,label in [(-.35,'−E_c'),(.35,'+E_c')]:s.dot(650+450*z,360,5);s.text(650+450*z-25,380,label,20)
        for sign,label in [(1,'+P_r'),(-1,'−P_r')]:
            y=360-sign*180*math.tanh(1.05);s.dot(650,y,5);s.text(670,y-8,label,20)
        s.text(150,640,'Differential relative permittivity: κ = 1 + (1/ε₀) dP/dE (on the chosen branch).',21,INK,1200)
        s.text(150,685,'The loop area ∮ E dP is dissipated energy per unit volume per cycle.',21,INK,1200)
    elif slug=='capacitors' and n in (23,25):
        divider=n==25
        s.title('Compensated divider: capacitor and resistor branches share the same nodes' if divider else 'DC steady state: capacitor open, resistor divider still connected',
                'Ideal components. Each drawn junction is a real electrical connection.')
        # A horizontal divider, input at A, output at B, return at C.
        def resistor(a,b,y,label):
            mid=(a+b)/2;s.line(a,y,mid-65,y);s.rect(mid-65,y-18,130,36,INK,WHITE);s.line(mid+65,y,b,y);s.text(mid-22,y-55,label,22)
        def capacitor(a,b,y,label):
            mid=(a+b)/2;s.line(a,y,mid-12,y);s.line(mid+12,y,b,y)
            s.line(mid-12,y-25,mid-12,y+25,BLUE,3);s.line(mid+12,y-25,mid+12,y+25,BLUE,3);s.text(mid-20,y-60,label,22,BLUE)
        for x,label in [(150,'A: V_s'),(650,'B: V_out'),(1150,'C: 0 V')]:s.dot(x,260,5);s.text(x-30,145,label,22,INK,250)
        resistor(150,650,260,'R₁');resistor(650,1150,260,'R₂')
        if divider:
            capacitor(150,650,430,'C₁');s.line(150,260,150,430)
        capacitor(650,1150,430,'C₂' if divider else 'C');s.line(650,260,650,430);s.line(1150,260,1150,430)
        if divider:
            s.text(150,530,'DC ratio = R₂/(R₁+R₂); instantaneous capacitive ratio = C₁/(C₁+C₂).',22,INK,1200)
            s.text(150,575,'Flat step response iff R₁C₁ = R₂C₂; then both ratios are equal.',22,BLUE,1200)
            s.text(150,620,'R₁C₁ > R₂C₂: initial output too high; R₁C₁ < R₂C₂: initial output too low.',21,INK,1200)
        else:
            s.text(150,530,'At DC steady state: I_C = 0. Current through R₁ and R₂ is V_s/(R₁+R₂).',22,INK,1200)
            s.text(150,575,'V_C(∞) = V_s R₂/(R₁+R₂); the capacitor is not a short circuit.',22,BLUE,1200)
            s.text(150,620,'For a step: τ = (R₁ ∥ R₂)C. An extra series resistor in the capacitor branch has no DC drop.',20,INK,1200)
    else:return None
    return s


def main():
    from tools.excalidraw_checks import validate_excalidraw
    electro=ROOT/'electrostatics';text=(electro/'Electrostatics.md').read_text()
    errors=validate_excalidraw(electro,text,[(str(13),str(n)) for n in range(1,27)])
    if errors:raise ValueError('\n'.join(errors))
    print('Electrostatics: existing 26 D13 scenes validated; untouched')
    for slug,(name,part,count) in TOPICS.items():
        master=ROOT/slug/name;source=master.read_text()
        matches=list(re.finditer(r'(?m)^!\[([^\n\]]+)\]\((assets/figures/fig-(\d+)\.svg)\)$',source))
        figures=sorted((ROOT/slug/'assets/figures').glob('fig-*.svg'))
        assert len(figures)==count and {int(m[3]) for m in matches}==set(range(1,count+1))
        mp=ROOT/slug/'figures.json';manifest=json.loads(mp.read_text());drawings=[]
        for n,fig in enumerate(figures,1):
            id_=f'D{part}.{n}';m=next(m for m in matches if int(m[3])==n)
            corrected=corrected_scene(slug,fig,id_);scene=corrected or converted_scene(slug,fig,id_)
            title=m[1];stem,file=scene_file(slug,id_,title,scene)
            show=('Analytic redraw correcting the legacy sketch; use this scene for geometry and signs.' if corrected
                  else 'Editable companion retaining source geometry, with reflowed labels and native primitives.')
            embed=f'![[../_obsidian/excalidraw/{stem}|900]]'
            block=(f'> [!abstract] DIAGRAM {id_} — {title}\n> **Show:** {show}\n'
                   f'> **Source:** `{slug}/{m[2]}`; original retained.\n'
                   f'> **Read:** {title.rstrip(".")}.\n\n{embed}')
            if embed in source:
                pattern=r'> \[!abstract\] DIAGRAM '+re.escape(id_)+r' —[^\n]*\n(?:(?:>[^\n]*|)\n)*'+re.escape(embed)
                source,hits=re.subn(pattern,lambda _:block,source)
                if hits!=1:raise ValueError(f'duplicate or missing brief: {id_}')
            else:source=source.replace(m[0],m[0]+'\n\n'+block,1)
            drawings.append(dict(id=id_,kind='excalidraw',title=title,show=show,
                                 search=f'Local source: {slug}/{m[2]}',file=file,
                                 source=f'{slug}/{name} · {m[2]}'))
        manifest.update(drawings=drawings,renderer='obsidian-excalidraw-plugin@2.27.3',
                        drawing_numbering='D17 Heat and D18 Capacitors continue the drawing series; course slots 16 and 18. Electrostatics at slot 17 retains D13.')
        manifest['note']=manifest['note'].replace('existing 24 reviewed','existing 25 reviewed')
        master.write_text(source);mp.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
        print(f'{slug}: {count} native companion scenes; originals preserved')


if __name__=='__main__':main()
